### ISSUE TITLE
Fix MT5 compile warnings: implicit conversion

### ISSUE THREAD

**Issue by xbotuk** [vivazzi/JAson#4]
- Fix MT5 compile warnings: implicit conversion from 'number' to 'string'	TestJAson.mq5

UDP 01.04.2022:
Issue "Convert the unit tests to be run as Scripts rather than as Experts" moved to https://github.com/vivazzi/JAson/issues/8

**Comment by vivazzi** [comment]
I separated this issue and added a new issue https://github.com/vivazzi/JAson/issues/8

**Comment by vivazzi** [comment]
dublicate https://github.com/vivazzi/mql_unit_test/issues/2
